### ISSUE TITLE
cannot use update(null, true)

### ISSUE THREAD

**Issue by ppetpadriew** [substack/js-traverse#58]
When traversing the object and if there are some null values in the object, an error is thrown.
Example code:
```javascript
var obj = {
    name: {
        en: null
    },
    price: 100
};
var result = traverse(obj).map(function (item) {
    if (this.key === 'en') {
        if(typeof item === 'undefined' || item === null ){
            this.parent.update(item, true);
            return;
        }
        this.parent.update(item);
    }
});
```

> TypeError: Cannot convert undefined or null to object
   at hasOwnProperty (native)
   at C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\node_modules\traverse\index.js:209:49
   at Array.forEach (native)
   at forEach (C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\node_modules\traverse\index.js:298:31)
   at walker (C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\node_modules\traverse\index.js:203:13)
   at C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\node_modules\traverse\index.js:208:29
   at Array.forEach (native)
   at forEach (C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\node_modules\traverse\index.js:298:31)
   at walker (C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\node_modules\traverse\index.js:203:13)
   at C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\node_modules\traverse\index.js:208:29
   at Array.forEach (native)
   at forEach (C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\node_modules\traverse\index.js:298:31)
   at walker (C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\node_modules\traverse\index.js:203:13)
   at walk (C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\node_modules\traverse\index.js:226:7)
   at Traverse.map (C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\node_modules\traverse\index.js:46:12)
   at Object.module.exports.filterContentByLanguage (C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\v1\components\localization-manager.js:8:36)
   at module.exports.pickContentBySelectedLanguage (C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\v1\routes\utility-route.js:144:49)
   at Layer.handle [as handle_request] (C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\node_modules\express\lib\router\route.js:131:13)
   at module.exports.bundleMallData (C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\v1\routes\coupon-route.js:222:13)
   at Layer.handle [as handle_request] (C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\Users\Turb-Laptop\Documents\bitbucket\shop-mania-api\node_modules\express\lib\router\route.js:131:13)

**Comment by ppetpadriew** [comment]
I've just create a pull request for this issue. Please kindly review it.
https://github.com/substack/js-traverse/pull/59
